config/routes.rb
SCInterface::Application.routes.draw do

  resources :workspace_relationships

  resources :customers
  
  resources :scratch_user
 
  
  resources :sc_admin_workspace
  resources :sc_admin_company
  resources :sc_admin_application
  resources :sc_admin_user
  resources :sc_admin_bill do
    get 'download_bill'
  end
  
  resources :forfaits
  resources :ecosystem_mecanic
  
  resources :members do
    resources :company
    resources :workspaces
  end
  
  resources :company do
    resources :members
    resources :workspaces
  end
  
  devise_for  :users,   :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" , :passwords => "users/passwords"}

  resources :laboratory
  resources :materials
  resources :links
  
  resources :calculs
  match 'calculs/duplicate'   => "calculs#duplicate" 
  
  match 'workspaces/get_gestionnaire'   => "workspaces#get_gestionnaire"  
  match 'workspaces/add_application'   => "workspaces#add_application"  
  resources :workspaces do
    resources :materials
    resources :links
    resources :forfaits
    get 'ecosystem_mecanic', :on => :member
    resources :sc_models do 
      post 'load_mesh', :on => :member
      get 'share', :on => :member
      get 'ecosystem_mecanic', :on => :member
    end
    
    resources :bills do
      get 'download_bill', :on => :member
      get 'cancel', :on => :member
    end
    resources :members
    resources :company
  end
  
  resources :sc_models do 
    resources :calculs
    resources :scult 
    resources :visualisation
  end
  
  

  root :to => "scratch_user#show"

  match ':controller(/:action(/:id(.:format)))'

  
  
  
  
  
  
  

end

app/models/physical/bill.rb
# encoding: utf-8

class Bill < ActiveRecord::Base
  belongs_to :workspace
  belongs_to :credit
  belongs_to :log_abonnement
  belongs_to :company
  
  scope :from_workspace , lambda { |workspace_id|
     where(:workspace_id => workspace_id)
   }
  
  # nouvelle facture associée à une ligne de crédit calcul
  def new_token_bill()
    self.bill_type = "token"
    self.statut = "unpaid"
    self.description = self.credit.forfait.name
    self.ref = Date.today.to_s() + "-" + self.id.to_s()  
    self.token_price_HT = self.credit.token_price
    self.global_price_HT = self.credit.global_price
    self.global_price_TVA = self.credit.global_price * 0.196
    self.global_price_TTC = self.credit.global_price * 1.196
    
    self.total_price_HT = self.global_price_HT
    self.total_price_TVA = self.global_price_TVA
    self.total_price_TTC = self.global_price_TTC
    
    #génération de la facture pdf et sauvegarde
    self.generate_bill_pdf()
    self.save
  end
  
  def valid_bill()
    if self.statut != "paid"
      self.statut = "paid"
      self.paid_date = Date.today
      self.save
      self.generate_bill_pdf()
      self.credit.valid_credit()
    end
  end
  
  def cancel_bill()
    self.statut = "canceled"
    self.save
    self.generate_bill_pdf()
    self.credit.cancel_credit()
  end
  
  #on génère le fichier pdf de la facture
  def generate_bill_pdf()
    
    @current_workspace = self.workspace
    @current_member_gestionnaire = @current_workspace.user_workspace_memberships.find(:first, :conditions => {:manager => 1})
    @current_gestionnaire = @current_member_gestionnaire.user
    pdf = Prawn::Document.new(:page_size => 'A4', :margin => [0,0,0,0])
    
    pdf.font "Helvetica" 
    colors = {:black => "000000", :grey => "8d8d8d", :blue => "2a3556", :magenta => "eb4f95", :white => "ffffff"} 
    pdf.line_width = 0.75
    pdf.stroke_color colors[:grey]

    logoimage = "public/images/logo.jpg" 
    #pdf.bounding_box [50, 820], :width => 150, :height => 100 do
    pdf.bounding_box [0, 850], :width => 820, :height => 120 do
	#pdf.stroke_bounds
        #pdf.image "public/images/Logo_StructureComputation_bleu.png", :scale => 1, :position  => :left, :vposition  => :top
        pdf.image "public/images/entete.png", :scale => 0.725, :position  => :left, :vposition  => :top
    end

    pdf.fill_color colors[:blue]
    pdf.bounding_box [250, 720], :width => 100, :height => 30 do
	pdf.text "Facture", :size => 20, :align => :center
    end
#     pdf.fill_color colors[:blue]
#     pdf.stroke_horizontal_line(0,595)


    pdf.bounding_box([50, 650], :width => 100, :height => 150) do
	pdf.fill_color colors[:blue]
	pdf.text "Référence : " , :align => :left , :style => :bold
	pdf.move_down(5)
	pdf.text "Date : ", :align => :left , :style => :bold
	pdf.move_down(5)
	pdf.text "Statut : " , :align => :left, :style => :bold
    end

    pdf.bounding_box [150, 650], :width => 100, :height => 150 do
	pdf.fill_color colors[:blue]
	pdf.text self.ref , :align => :left
	pdf.move_down(5)
	pdf.text self.created_at.to_date.to_s(), :align => :left
	pdf.move_down(5)
	pdf.text self.statut, :align => :left
    end

    pdf.bounding_box [300, 650], :width => 245, :height => 150 do
	pdf.text @current_gestionnaire.firstname + " " + @current_gestionnaire.lastname , :align => :right
	pdf.text @current_workspace.name, :align => :right
        pdf.text "  ", :align => :right
	pdf.text self.company.name, :align => :right
	pdf.text self.company.address, :align => :right
	pdf.text self.company.zipcode + " " + self.company.city, :align => :right
	pdf.text self.company.phone, :align => :right
    end

    #entete du tableau des prix
    pdf.fill_color colors[:blue]
    pdf.bounding_box [360, 500], :width => 70, :height => 20 do
	pdf.text "€ HT ", :align => :center
    end
    pdf.bounding_box [430, 500], :width => 70, :height => 20 do
	pdf.text "€ TVA ", :align => :center
    end
    pdf.bounding_box [500, 500], :width => 70, :height => 20 do
	pdf.text "€ TTC ", :align => :center
    end

    # si le type de facture est un calcul ----------------------------------------------------------------
    if self.bill_type == 'token'
      # on insere les noms des lignes
      pdf.fill_color colors[:blue]
      pdf.bounding_box [50, 480], :width => 110, :height => 20 do
	  pdf.text  "Forfait de calcul :" , :align => :left, :style => :bold
      end
      pdf.bounding_box [160, 480], :width => 200, :height => 20 do
	  pdf.text  self.credit.forfait.name , :align => :left 
      end

      pdf.bounding_box [80, 465], :width => 150, :height => 45 do
	  pdf.text "Nombre de jetons :", :align => :left, :size => 10
	  pdf.text "Durée de validité (mois) :", :align => :left, :size => 10
      end
      pdf.bounding_box [230, 465], :width => 100, :height => 45 do
	  pdf.text self.credit.nb_token.to_s(), :align => :left, :size => 10
	  pdf.text self.credit.forfait.validity.to_s(), :align => :left, :size => 10
      end

      # on insere les chiffres
      pdf.fill_color colors[:blue]
      pdf.bounding_box [360, 480], :width => 70, :height => 20 do
	  pdf.text  self.global_price_HT.to_s() , :align => :center
      end
      pdf.bounding_box [430, 480], :width => 70, :height => 20 do
	  pdf.text  self.global_price_TVA.to_s(), :align => :center
      end
      pdf.bounding_box [500, 480], :width => 70, :height => 20 do
	  pdf.text  self.global_price_TTC.to_s(), :align => :center
      end

      pdf.fill_color colors[:blue]
      pdf.bounding_box [360, 465], :width => 70, :height => 45 do
	  pdf.text " - ", :align => :center, :size => 10
	  pdf.text " - ", :align => :center, :size => 10
      end
      pdf.bounding_box [430, 465], :width => 70, :height => 45 do
	  pdf.text " - ", :align => :center, :size => 10
	  pdf.text " - ", :align => :center, :size => 10
      end
      pdf.bounding_box [500, 465], :width => 70, :height => 45 do
	  pdf.text " - ", :align => :center, :size => 10
	  pdf.text " - ", :align => :center, :size => 10
      end
    end

    # totale de la facture
    pdf.stroke_color colors[:blue]
    pdf.stroke_horizontal_line(200,570) 

    pdf.bounding_box [210, 410], :width => 70, :height => 20 do
	pdf.text  "Total" , :align => :center, :style => :bold
    end
    pdf.bounding_box [360, 410], :width => 70, :height => 20 do
	pdf.text  self.total_price_HT.to_s() , :align => :center, :style => :bold
    end
    pdf.bounding_box [430, 410], :width => 70, :height => 20 do
	pdf.text  self.total_price_TVA.to_s(), :align => :center, :style => :bold
    end
    pdf.bounding_box [500, 410], :width => 70, :height => 20 do
	pdf.text  self.total_price_TTC.to_s(), :align => :center, :style => :bold
    end

    pdf.bounding_box [50, 380], :width => 500, :height => 150 do
    end
    
    pdf.fill_color colors[:grey]
    pdf.stroke_color colors[:grey]
    
    # mentions légales
    pdf.bounding_box [50, 220], :width => 500, :height => 100 do
        pdf.text "RIB" , :align => :center, :size => 10
        pdf.text "Banque   Guichet    N°compte        Clé          Devise" , :align => :center, :size => 10
        pdf.text "30066     10633    00020036101      16            EUR  " , :align => :center, :size => 10
        pdf.text "   " , :align => :center, :size => 10
        pdf.text "IBAN" , :align => :center, :size => 10
        pdf.text "FR76 3006 6106 3300 0200 3610 116" , :align => :center, :size => 10
    end
    
    pdf.stroke_horizontal_line(0,595)
    pdf.bounding_box [50, 100], :width => 500, :height => 80 do
        pdf.text "Structure Computation, 86 rue de Paris, 91400 Orsay" , :align => :center, :size => 10
        pdf.text "www.structure-computation.com, contact@structure-computation.com" , :align => :center, :size => 10
        pdf.text "SAS au capital de 45 000 €" , :align => :center, :size => 10
        pdf.text "SIREN : 514 972 306 " , :align => :center, :size => 10
    end     
    
    #enregistrement du fichier pdf
    pdf.render_file "#{SC_FACTURE_ROOT}/facture_" + self.id.to_s() + ".pdf"
    
  end
end

app/controllers/bills_controller.rb
# encoding: utf-8

class BillsController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :must_be_manager
  before_filter :set_page_name
  respond_to :html, :json
  belongs_to :workspace
  actions :index, :show, :new, :create, :cancel
  layout 'workspace'
  
  def set_page_name
    @page = :manage
  end              
  
  def index 
    @workspace  = current_workspace_member.workspace
    @bills      = Bill.from_workspace @workspace.id
    index!
  end        
                                                      
  def show 
    @workspace = current_workspace_member.workspace
    @bill      = Bill.from_workspace(@workspace.id).find_by_id(params[:id])
    if @bill.statut == "canceled"
      redirect_to workspace_path(current_workspace_member.workspace), :notice => "Cette facture a été annulée" # TODO traduire 
    else        
      render
    end                                  
  end 
  
  def cancel 
    @workspace = current_workspace_member.workspace
    @bill      = Bill.from_workspace(@workspace.id).find_by_id(params[:id])
    @bill.cancel_bill()        
    redirect_to workspace_path(current_workspace_member.workspace), :notice => "La facture a été annulée" # TODO traduire                            
  end 
  
  def pay 
    @workspace = current_workspace_member.workspace
    @bill      = Bill.from_workspace(@workspace.id).find_by_id(params[:id])
    redirect_to workspace_path(current_workspace_member.workspace), :notice => "La facture a été payée" # TODO traduire                                 
  end 

  def download_bill
    @current_workspace = current_workspace_member.workspace
    @current_bill = @current_workspace.bills.find(params[:id])
    name_file = "#{SC_FACTURE_ROOT}/facture_" + params[:id] + ".pdf"
    name_bill = 'Facture_' + @current_bill.ref.to_s() + '.pdf'
    send_file name_file, :filename => name_bill
  end

  def generate_pdf_facture
    @current_workspace = current_workspace_member.workspace
    @current_bill = @current_workspace.bills.find(params[:id_facture])
    @current_gestionnaire = @current_workspace.users.find(:first, :conditions => {:role => "gestionnaire"})
    prawnto :inline => false
    prawnto :prawn => { 
                 :background => "#{RAILS_ROOT}/public/images/fond_facture.jpg", 
                 :left_margin => 0, 
                 :right_margin => 0, 
                 :top_margin => 0, 
                 :bottom_margin => 0, 
                 :page_size => 'A4' }

    respond_to do |format|
      format.pdf {render :layout => false }
    end
  end
    
end

app/helpers/bills_helper.rb
# encoding: utf-8

module BillsHelper
end

app/views/bills/_bill_detail.html.haml
-# encoding: utf-8 
%table.grey
  %thead
    %tr.no_sorter
      %th
      %th € HT
      %th € TVA
      %th € TTC
  %body

    %tr
      %td= @bill.credit.forfait.name
      %td= @bill.global_price_HT
      %td= @bill.global_price_TVA
      %td= @bill.global_price_TTC
    %tr
      %td 
        Nombre de jetons : 
        = @bill.credit.forfait.nb_token
      %td -
      %td -
      %td -
    %tr
      %td 
        Durée de validité (mois) : 
        = @bill.credit.forfait.validity
      %td -
      %td -
      %td -

    %tr
      %td Total
      %td= @bill.total_price_HT
      %td= @bill.total_price_TVA
      %td= @bill.total_price_TTC

app/views/bills/_bills_list.html.haml
-# encoding: utf-8 
.search_filter
  %p
    %label{:for => "bills_search_filter"} Recherche
    %input#bills_search_filter{:type => "text"}

%table.grey#bills_table
  %thead
    %tr
      %th.no_sorter
      %th Référence
      %th Type
      %th Prix HT(Euros)
      %th Prix TTC(Euros)
      %th Status
      %th.no_sorter Actions
  %body
    - bills_list.each do |bill|
      %tr
        %td.escape_search.details_link= link_to "Détails", [@workspace, bill]      
        %td= bill.ref
        %td= bill.bill_type
        %td= bill.total_price_HT
        %td= bill.total_price_TTC
        %td= bill.statut
        %td.action_on_table.escape_search
          -if bill.statut != "canceled"
            %ul
              %li 
                = link_to "pdf", download_bill_workspace_bill_path(@workspace, bill)
              -if bill.statut != "paid"
                %li
                  /= button_to "Annuler", cancel_workspace_bill_path(@workspace, bill), :confirm => "Êtes-vous sûr ?"
                  = button_to "Annuler", {:controller => :bills, :action => :cancel, :id => bill.id}, :confirm => "Êtes-vous sûr ?"
                %li 
                  = link_to "payer en ligne",  :controller => :bills, :action => :pay, :id => bill.id

:coffeescript
  $( ->
    $('#bills_table').tablesorter()

    searchFilter("bills_table", "bills_search_filter")
  )

app/views/bills/_facture_detail.html.haml
%table.grey
  %thead
    %tr
      %th
      %th € HT
      %th € TVA
      %th € TTC
  %body

    %tr
      %td 
        - if @bill.facture_type == "memoire"
          Abonnement espace mémoire :
          = @bill.log_abonnement.abonnement.name
        - elsif @bill.facture_type == "calcul"
          Forfait de calcul :
          = @bill.credit.forfait.name
      %td= @bill.total_price_HT
      %td= @bill.total_price_TVA
      %td= @bill.total_price_TTC
    %tr
      %td 
        - if @bill.facture_type == "memoire"
          Mémoire assigné
          = @bill.log_abonnement.abonnement.assigned_memory
        - elsif @bill.facture_type == "calcul"
          Nombre de jetons standard
          = @bill.credit.forfait.nb_jetons
      %td -
      %td -
      %td -
    %tr
      %td 
        - if @bill.facture_type == "memoire"
          Niveau de sécurité
          = @bill.log_abonnement.abonnement.security_level
        - elsif @bill.facture_type == "calcul"
          Nombre de jetons tampons :
          = @bill.credit.forfait.nb_jetons_tempon
      %td -
      %td -
      %td -
    %tr
      %td 
        - if @bill.facture_type == "memoire"
          Nombre d'utilisateur maximum
          = @bill.log_abonnement.abonnement.nb_max_user
        - elsif @bill.facture_type == "calcul"
          Durée de validité (mois) : 
          = @bill.credit.forfait.validity
      %td -
      %td -
      %td -

    %tr
      %td Total
      %td= @bill.total_price_HT
      %td= @bill.total_price_TVA
      %td= @bill.total_price_TTC

app/views/bills/index.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_submenu
    %h2.grey
      Menu
    %ul
      %li.manage_pic_compte_memoire
        = link_to "Nouvel abonnement", workspace_sc_models_path(@workspace) 
      %li.manage_pic_compte_abonnement
        = link_to "Nouveau forfait", workspace_sc_models_path(@workspace)
                 
-content_for :right_top do
  %h2.grey
    Liste des factures

-content_for :workspace_content do
  =render :partial => 'bills_list', :object => @workspace.bills

app/views/bills/show.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_submenu
    %h2.grey
      Menu
    %ul
      %li.manage_pic_liste_factures
        = link_to "Retour au workspace", workspace_path(@workspace, :anchor => 'Factures') 
      %li.manage_pic_liste_factures
        = link_to "Télécharger la facture", download_bill_workspace_bill_path(@workspace, @bill)
      %li.manage_pic_liste_factures
        = link_to "Payer en ligne", :controller => :bills, :action => :pay, :id => @bill.id
      %li.manage_pic_liste_factures
        = link_to "Annuler", :controller => :bills, :action => :cancel, :state => "canceled", :id => @bill.id
        
-content_for :right_top do
  %h2.grey
    Référence Facture : 
    = @bill.ref
  .grey
    %p
      %tr
        %td
          Date :
        %td
          = @bill.created_at.to_date
        %td
          Status :
        %td
          = @bill.statut       
    %p 
      Responsable : 
      %br
      = @bill.company.firstname + " " +  @bill.company.lastname
      %br
      = @bill.company.phone

    %p 
      Société : 
      %br
      = @bill.company.address
      %br
      = @bill.company.zipcode  + " " +  @bill.company.city
      %br
      = @bill.company.country
        

-content_for :workspace_content do
  = render :partial => 'bill_detail', :object => @bill