config/routes.rb
SCInterface::Application.routes.draw do

  resources :workspace_relationships

  resources :customers
  
  resources :scratch_user
 
  
  resources :sc_admin_workspace
  resources :sc_admin_company
  resources :sc_admin_application
  resources :sc_admin_user
  resources :sc_admin_bill do
    get 'download_bill'
  end
  
  resources :forfaits
  resources :ecosystem_mecanic
  
  resources :members do
    resources :company
    resources :workspaces
  end
  
  resources :company do
    resources :members
    resources :workspaces
  end
  
  devise_for  :users,   :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" , :passwords => "users/passwords"}

  resources :laboratory
  resources :materials
  resources :links
  
  resources :calculs
  match 'calculs/duplicate'   => "calculs#duplicate" 
  
  match 'workspaces/get_gestionnaire'   => "workspaces#get_gestionnaire"  
  match 'workspaces/add_application'   => "workspaces#add_application"  
  resources :workspaces do
    resources :materials
    resources :links
    resources :forfaits
    get 'ecosystem_mecanic', :on => :member
    resources :sc_models do 
      post 'load_mesh', :on => :member
      get 'share', :on => :member
      get 'ecosystem_mecanic', :on => :member
    end
    
    resources :bills do
      get 'download_bill', :on => :member
      get 'cancel', :on => :member
    end
    resources :members
    resources :company
  end
  
  resources :sc_models do 
    resources :calculs
    resources :scult 
    resources :visualisation
  end
  
  

  root :to => "scratch_user#show"

  match ':controller(/:action(/:id(.:format)))'

  
  
  
  
  
  
  

end

app/models/company_account.rb
class CompanyAccount < ActiveRecord::Base
end

app/models/fillial.rb
# encoding: utf-8

class Fillial < ActiveRecord::Base
end

app/controllers/sc_admin_workspace_controller.rb
# encoding: utf-8

class ScAdminWorkspaceController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :valid_admin_user
  before_filter :set_page_name
  
  layout 'sc_admin'
  
  def set_page_name
    @page = :sc_admin_workspace
  end
  
  def index 
    @workspaces = Workspace.all
    if params[:notice] 
      flash[:notice] = params[:notice]
    end
  end
  
  def show
    @workspace    = Workspace.find_by_id(params[:id])
    @credits      = @workspace.token_account.credits.find(:all, :conditions => {:state => "active"})
    @soldes       = @workspace.token_account.solde_token_accounts.find(:all, :order => " created_at DESC")
    if params[:notice] 
      flash[:notice] = params[:notice]
    end
    if @workspace 
      # show!
      render
    else
      respond_to do |format|
        format.html {redirect_to :action => :index, 
                    :notice => "Ce workspace n'existe pas ou n'est pas accessible à partir de cette page."}
        format.json {render :status => 404, :json => {}}
      end
    end
  end
  
  def new
    @workspace = Workspace.new
  end
  
  def create
    @new_workspace = Workspace.create(params[:workspace])
    @new_workspace.init_account
    if @new_workspace 
      respond_to do |format|
        format.html {redirect_to :action => :index, 
                    :notice => "Nouveau workspace créée."}
        format.json {render :status => 404, :json => {}}
      end
    else
      respond_to do |format|
        format.html {redirect_to :action => :index, 
                    :notice => "Le workspace n'a pas été créé."}
        format.json {render :status => 404, :json => {}}
      end
    end
  end
  
  def edit
    @workspace = Workspace.find_by_id(params[:id])
  end
  
end

app/helpers/bills_helper.rb
# encoding: utf-8

module BillsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
# encoding: utf-8

module CompanyHelper
end

app/helpers/credit_helper.rb
# encoding: utf-8

module CreditHelper
end

app/helpers/customer_helper.rb
# encoding: utf-8

module CustomerHelper
end

app/helpers/customers_helper.rb
# encoding: utf-8

module CustomersHelper
end

app/helpers/forfaits_helper.rb
# encoding: utf-8

module ForfaitsHelper
end

app/helpers/home_helper.rb
# encoding: utf-8

module HomeHelper
end

app/helpers/link_helper.rb
# encoding: utf-8

module LinkHelper
end

app/helpers/log_tools_helper.rb
# encoding: utf-8

module LogToolsHelper
end

app/helpers/materials_helper.rb
# encoding: utf-8

module MaterialsHelper
end

app/helpers/members_helper.rb
# encoding: utf-8

module MembersHelper
end

app/helpers/sc_admin_workspace_helper.rb
# encoding: utf-8

module ScAdminWorkspaceHelper
end

app/helpers/sceen_helper.rb
# encoding: utf-8

module SceenHelper
end

app/helpers/score_helper.rb
# encoding: utf-8

module ScoreHelper
end

app/helpers/scult_helper.rb
# encoding: utf-8

module ScultHelper
end

app/helpers/sessions_helper.rb
# encoding: utf-8

module SessionsHelper
end

app/helpers/static_helper.rb
# encoding: utf-8

module StaticHelper
end

app/helpers/users_helper.rb
# encoding: utf-8

module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/sc_admin_workspace/_form.html.haml
-# encoding: utf-8 
%p
= semantic_form_for @workspace, :url => {:controller => "sc_admin_workspace", :action => "create"}  do |form|
  %table.grey#workspace_information_table
    %tr
      %th Name
      %td= form.text_field :name
    %tr
      %th Description publique
      %td= form.text_area :public_description

  = form.buttons

app/views/sc_admin_workspace/_search_filter.html.haml
-# encoding: utf-8 
.search_filter
  %p
    %label{:for => "search_filter"} Recherche
    %input#search_filter{:type => "text"}
    %button#more_details.close.yellow_button Recherche avancée

  #workspaces_advanced_search.advanced_search
    %p
      %label{:for => "name_search_filter"} Nom
      %input#name_search_filter{:type => "text"}
    %p      
      %label{:for => "id_search_filter"} ID
      %input#id_search_filter{:type => "text"}    


:coffeescript
  $( ->
    $('#workspaces_table').tablesorter()

    $('#more_details').click( () ->
      $('#workspaces_advanced_search').toggleClass('maximize')
    )

    advancedSearchFilter("workspaces_table",
                         ["name_search_filter","id_search_filter"],
                         ["name"              ,"id"])
    searchFilter("workspaces_table", "search_filter")
  )

app/views/sc_admin_workspace/_workspaces_list.html.haml
-# encoding: utf-8 
%table#workspaces_table.grey
  %thead
    %tr
      %th.no_sorter
      %th ID
      %th Nom
      %th Description
      %th.no_sorter Actions
  %tbody
    - workspaces_list.each do |workspace|
      %tr
        %td.escape_search.details_link= link_to "Détails", sc_admin_workspace_path(workspace)
        %td= workspace.id
        %td= workspace.name
        %td= workspace.public_description
        %td.action_on_table.escape_search
          %ul
            %li
              = button_to "Supprimer", sc_admin_workspace_path(workspace), :confirm => "Êtes vous sûr ?", :method => :delete, :confirm => "Êtes-vous sûr ?"
            %li 
              = link_to "Editer", edit_sc_admin_workspace_path(workspace)

/= link_to 'Ajouter un membre', new_workspace_member_path(@workspace), :class => 'yellow_button'

:coffeescript
  $('#workspaces_table').tablesorter()

app/views/sc_admin_workspace/edit.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_submenu
    %h2.grey
      Menu
    %ul
      %li.LM_pic_model
        = link_to "Retour à la liste des workspaces", :controller => "sc_admin_workspace" 
-content_for :workspace_content do
  .grey
    = render "form"

app/views/sc_admin_workspace/index.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_submenu
    %h2.grey
      Menu
    %ul
      %li.LM_pic_new_model
        = link_to "Nouveau workspace", new_sc_admin_workspace_path  

-content_for :right_top do
  %h2.grey
    Liste des workspace 
  %div
    = render :partial => "search_filter"

-content_for :workspace_content do
  %table.grey#workspaces_table
    %thead
      %tr
        %th.no_sorter
        %th Nom
        %th ID
        %th.no_sorter Actions
    %tbody
      - @workspaces.each do |workspace|
        %tr
          %td.escape_search.details_link= link_to 'Détails' , sc_admin_workspace_path(workspace.id)
          %td.name=           workspace.name ? workspace.name : 'Undefined'
          %td.id=             workspace.id
          %td.action_on_table.escape_search
            %ul
              %li
                %a Visualisation
              %li
                %a Calcul
              %li
                = button_to 'Supprimer', sc_admin_workspace_path(workspace.id), :method => :delete, :confirm => "Êtes-vous sûr ?"

app/views/sc_admin_workspace/new.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_submenu
    %h2.grey
      Menu
    %ul
      %li.LM_pic_model
        = link_to "Retour à la liste des workspaces", :controller => "sc_admin_workspace" 
-content_for :workspace_content do
  .grey
    = render "form"

app/views/sc_admin_workspace/show.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_top
    %h2.grey
      Comptes
    %ul
      %li.manage_pic_compte_abonnement
        = link_to 'Nouveau forfait', :controller => "forfait", :action => "index"
      %li.manage_pic_nouveau_membre
        = link_to 'Ajouter un membre', new_workspace_member_path(@workspace)
      %li.manage_pic_nouveau_membre
        = link_to 'Editer', edit_sc_admin_workspace_path(@workspace)

-content_for :right_top do
  %h2.grey
    = @workspace.name
  .grey
    %p 
      = "Solde du compte de jetons : " + @workspace.token_account.solde_token.to_s
    
-content_for :workspace_content do
  %h2.grey
    Détails de la société
  .wrapper
    #left_content
      %ul.tab_submenu.js_tab_submenu  
        %li 
          %a#tab_1{:href => "#Factures"} Factures
        %li 
          %a#tab_2{:href => "#Compte"} Compte
        %li                    
          %a#tab_3{:href => "#Forfait"} Forfait
        %li                    
          %a#tab_4{:href => "#Membres"} Membres
        %li                    
          %a#tab_5{:href => "#Consortium"} Consortium
        %li                    
          %a#tab_6{:href => "#Description"} Description
            
    #right_content
      .tab_content.js_tab_content
        #tab_1_content
          %h3 Liste des factures de la société :
          = render :partial => 'sc_admin_bill/bills_list', :object => @workspace.bills.find(:all, :order=> " created_at DESC")
          
        #tab_2_content
          %p Solde du compte de jetons
          %p Compteurs globaux :
          %table.grey
            -#TODO afficher les bonnes valeurs
            %thead
              %tr.no_sorter
                %th Compteur de jetons utilisés
                %th Compteur de jetons achetés
                %th Solde courrant
                %th Jetons réservés
            %tbody
              %tr
                %td= @workspace.token_account.used_token_counter
                %td= @workspace.token_account.purchased_token_counter
                %td= @workspace.token_account.solde_token
                %td= @workspace.token_account.reserved_token
          %p Compte détaillé :
          = render :partial => "workspaces/soldes_list", :object => @soldes
                
        #tab_3_content
          %h3 Liste de vos forfait en cours d utilisation :
          = render :partial => 'credit/credits_list', :object => @credits
                
        #tab_4_content
          = render :partial => "members/search_filter"
          = render :partial => "sc_admin_user/members_list", :object => @workspace.members

        #tab_5_content
          = render :partial => "company/search_filter"
          = render :partial => "sc_admin_company/companies_list", :object => @workspace.companies
          
        #tab_6_content
          %table.grey#workspace_information_table
            %tr
              %th Name
              %td= @workspace.name
            %tr
              %th Public_description
              %td= @workspace.public_description  

      = coffeescript_include_tag "manage_tab"