config/routes.rb
SCInterface::Application.routes.draw do

  resources :workspace_relationships

  resources :customers
  
  resources :scratch_user
 
  
  resources :sc_admin_workspace
  resources :sc_admin_company
  resources :sc_admin_application
  resources :sc_admin_user
  resources :sc_admin_bill do
    get 'download_bill'
  end
  
  resources :forfaits
  resources :ecosystem_mecanic
  
  resources :members do
    resources :company
    resources :workspaces
  end
  
  resources :company do
    resources :members
    resources :workspaces
  end
  
  devise_for  :users,   :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" , :passwords => "users/passwords"}

  resources :laboratory
  resources :materials
  resources :links
  
  resources :calculs
  match 'calculs/duplicate'   => "calculs#duplicate" 
  
  match 'workspaces/get_gestionnaire'   => "workspaces#get_gestionnaire"  
  match 'workspaces/add_application'   => "workspaces#add_application"  
  resources :workspaces do
    resources :materials
    resources :links
    resources :forfaits
    get 'ecosystem_mecanic', :on => :member
    resources :sc_models do 
      post 'load_mesh', :on => :member
      get 'share', :on => :member
      get 'ecosystem_mecanic', :on => :member
    end
    
    resources :bills do
      get 'download_bill', :on => :member
      get 'cancel', :on => :member
    end
    resources :members
    resources :company
  end
  
  resources :sc_models do 
    resources :calculs
    resources :scult 
    resources :visualisation
  end
  
  

  root :to => "scratch_user#show"

  match ':controller(/:action(/:id(.:format)))'

  
  
  
  
  
  
  

end

app/models/company_account.rb
class CompanyAccount < ActiveRecord::Base
end

app/models/fillial.rb
# encoding: utf-8

class Fillial < ActiveRecord::Base
end

app/controllers/laboratory_controller.rb
# encoding: utf-8

class LaboratoryController < InheritedResources::Base
  before_filter :authenticate_user!  
  before_filter :must_be_engineer
  before_filter :set_page_name
  belongs_to :workspace
  
  layout 'workspace'
#  belongs_to :member
  
  def set_page_name
    @page = :lab
  end
  
  def index
    @workspace                  = current_workspace_member.workspace
    @sc_models                  = current_workspace_member.sc_models
    #@sc_models                  = ScModel.from_workspace @workspace.id
    @standard_materials         = Material.standard  
    @workspace_materials        = Material.from_workspace @workspace.id
    @standard_links             = Link.standard
    @workspace_links            = Link.from_workspace @workspace.id
    
  end
  
end

app/helpers/bills_helper.rb
# encoding: utf-8

module BillsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
# encoding: utf-8

module CompanyHelper
end

app/helpers/credit_helper.rb
# encoding: utf-8

module CreditHelper
end

app/helpers/customer_helper.rb
# encoding: utf-8

module CustomerHelper
end

app/helpers/customers_helper.rb
# encoding: utf-8

module CustomersHelper
end

app/helpers/forfaits_helper.rb
# encoding: utf-8

module ForfaitsHelper
end

app/helpers/home_helper.rb
# encoding: utf-8

module HomeHelper
end

app/helpers/laboratory_helper.rb
# encoding: utf-8

module LaboratoryHelper
end

app/helpers/link_helper.rb
# encoding: utf-8

module LinkHelper
end

app/helpers/log_tools_helper.rb
# encoding: utf-8

module LogToolsHelper
end

app/helpers/materials_helper.rb
# encoding: utf-8

module MaterialsHelper
end

app/helpers/members_helper.rb
# encoding: utf-8

module MembersHelper
end

app/helpers/sceen_helper.rb
# encoding: utf-8

module SceenHelper
end

app/helpers/score_helper.rb
# encoding: utf-8

module ScoreHelper
end

app/helpers/scult_helper.rb
# encoding: utf-8

module ScultHelper
end

app/helpers/sessions_helper.rb
# encoding: utf-8

module SessionsHelper
end

app/helpers/static_helper.rb
# encoding: utf-8

module StaticHelper
end

app/helpers/users_helper.rb
# encoding: utf-8

module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/laboratory/index.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_top
    %h2.grey
      Comptes
    %ul
      %li.LM_pic_new_model
        = link_to "Nouveau Projet", new_workspace_sc_model_path(@workspace)
      %li.LM_pic_new_mat
        = link_to "Nouveau materiau", new_workspace_material_path(@workspace)
      %li.LM_pic_new_liaison
        = link_to 'Nouvelle liaison', new_workspace_link_path(@workspace)

-content_for :right_top do
  %h2.grey
    = @workspace.name
  .grey
    %p 
      = "Solde du compte de jetons : " + @workspace.token_account.solde_token.to_s
    
-content_for :workspace_content do
  %h2.grey
    Détails du workspace
  .wrapper
    #left_content
      %ul.tab_submenu.js_tab_submenu
        %li 
          %a#tab_1{:href => "#Projets"} Projets
        %li 
          %a#tab_2{:href => "#Matériaux"} Matériaux
        %li                    
          %a#tab_3{:href => "#Liaisons"} Liaisons
            
    #right_content
      .tab_content.js_tab_content
        #tab_1_content
          %h3 Liste des modèles :
          = render :partial => 'sc_models/search_filter'
          = render :partial => 'sc_models/sc_models_list', :object => @sc_models
          
        #tab_2_content
          %h3 Liste des matériaux :
          = render :partial => 'materials/simple_search_filter'
          %table.grey#materials_table
            %thead
              %tr
                %th.no_sorter 
                %th Nom
                %th ID
                %th Famille
                %th Type
                %th Comportement
                %th.no_sorter Actions
            %tbody
              = render :partial => "materials/material", :collection => @standard_materials, :locals => {:type => "standard"}
              = render :partial => "materials/material", :collection => @workspace_materials,  :locals => {:type => "workspace"}
                
        #tab_3_content
          %h3 Liste des liaisons :
          = render :partial => 'links/simple_search_filter'
          %table.grey#links_table
            %thead
              %tr
                %th.no_sorter
                %th ID
                %th Nom
                %th Famille
                %th Générique
                %th Complexe
                %th.no_sorter Actions
            %tbody
              = render :partial => "links/link", :collection => @standard_links, :locals => {:type => "standard"}
              = render :partial => "links/link", :collection => @workspace_links,  :locals => {:type => "workspace"} 

      = coffeescript_include_tag "manage_tab"