config/routes.rb
SCInterface::Application.routes.draw do

  resources :workspace_relationships

  resources :customers
  
  resources :scratch_user
 
  
  resources :sc_admin_workspace
  resources :sc_admin_company
  resources :sc_admin_application
  resources :sc_admin_user
  resources :sc_admin_bill do
    get 'download_bill'
  end
  
  resources :forfaits
  resources :ecosystem_mecanic
  
  resources :members do
    resources :company
    resources :workspaces
  end
  
  resources :company do
    resources :members
    resources :workspaces
  end
  
  devise_for  :users,   :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :confirmations => "users/confirmations" , :passwords => "users/passwords"}

  resources :laboratory
  resources :materials
  resources :links
  
  resources :calculs
  match 'calculs/duplicate'   => "calculs#duplicate" 
  
  match 'workspaces/get_gestionnaire'   => "workspaces#get_gestionnaire"  
  match 'workspaces/add_application'   => "workspaces#add_application"  
  resources :workspaces do
    resources :materials
    resources :links
    resources :forfaits
    get 'ecosystem_mecanic', :on => :member
    resources :sc_models do 
      post 'load_mesh', :on => :member
      get 'share', :on => :member
      get 'ecosystem_mecanic', :on => :member
    end
    
    resources :bills do
      get 'download_bill', :on => :member
      get 'cancel', :on => :member
    end
    resources :members
    resources :company
  end
  
  resources :sc_models do 
    resources :calculs
    resources :scult 
    resources :visualisation
  end
  
  

  root :to => "scratch_user#show"

  match ':controller(/:action(/:id(.:format)))'

  
  
  
  
  
  
  

end

app/models/physical/credit.rb
# encoding: utf-8

class Credit < ActiveRecord::Base
  belongs_to :token_account
  belongs_to :forfait
  has_one    :workspace ,  :through => :token_account
  has_one    :solde_token_account
  has_one    :bill
  
  #state : pending, active, canceled
  # nouvelle ligne de crédit et nouvelle facture non validé
  def create_credit_and_bill(forfait_id, company_id)
    forfait = Forfait.find(forfait_id)
    company = Company.find(company_id)
    
    #initialisation de la ligne de credit
    self.forfait = forfait
    self.nb_token = forfait.nb_token
    self.token_price = forfait.token_price
    self.global_price = forfait.global_price 
    self.solde_token = forfait.nb_token
    self.used_token = 0
    self.state = "pending"
    
    #création de la facture
    current_bill = self.build_bill() 
    current_bill.workspace = self.token_account.workspace
    current_bill.company = company
    current_bill.save
    
    #derniere mise a jour des info du compte et sauvegarde
    self.save
    current_bill.new_token_bill()
  end
  
  # validation de la ligne de credit et sauvegarde du compte après paiement de la facture
  def valid_credit()
    self.state = "active"
    self.end_date = Date.today + self.forfait.validity.month
    self.save
    self.token_account.valid_credit(self.id)
  end
  
  def cancel_credit()
    self.state = "canceled"
    self.end_date = Date.today
    self.save
  end
  
end

app/controllers/credit_controller.rb
# encoding: utf-8

class CreditController < InheritedResources::Base
  before_filter :authenticate_user!  
  before_filter :must_be_manager
  before_filter :set_page_name
  
  layout 'workspace'
  
  def set_page_name
    @page = :manage
  end
  
  def new
    @workspace  = current_workspace_member.workspace
    @forfait    = Forfait.find(params[:forfait_id])
    @new_company = Company.new()
  end
  
  def create
    @workspace  = current_workspace_member.workspace
    @forfait    = Forfait.find(params[:forfait_id])
    @company_id = -1
    if params[:informations] == "new"
      @company    = @workspace.companies.create(params[:company])
      @company_id = @company.id
      logger.debug @company.id
      logger.debug current_user.id
      current_user.companies << @company
      #@company.members << current_user  
    elsif params[:informations] == "exist"
      @company    = @workspace.companies.find(params[:company_id])
      if current_user.companies.exists?(@company.id)
        #@company.members << current_user
        current_user.companies << @company
      end
      @company_id = params[:company_id]
    else
      redirect_to workspace_path(@workspace), :notice => "Suite à un problème, le nouveau forfait n'a pas été souscrit. vauillez recommencer l'opération" # TODO traduire
    end
    logger.debug @company_id
    logger.debug @forfait.id
    @credit     = @workspace.token_account.credits.build()
    @credit.create_credit_and_bill(@forfait.id,@company_id)
    if @credit 
      redirect_to workspace_path(@workspace), :notice => "Nouveau forfait souscrit, une facture a été générée." # TODO traduire 
    else
      redirect_to workspace_path(@workspace), :notice => "Suite à un problème, le nouveau forfait n'a pas été souscrit. vauillez recommencer l'opération" # TODO traduire 
    end 
  end
  
end

app/helpers/credit_helper.rb
# encoding: utf-8

module CreditHelper
end

app/views/credit/_companies_list.html.haml
-# encoding: utf-8 
%table#companies_table.grey
  %thead
    %tr
      %th.no_sorter
      %th Responsable
      %th Téléphone
      %th Société
      %th Adresse
  %tbody
    - companies_list.each do |company|
      %tr
        %td.escape_search.details_link= link_to "Valider", :controller => "credit", :action => "create", :forfait_id => @forfait.id, :company_id => company.id, :informations => "exist"
        %td= company.firstname + " " + company.lastname
        %td= company.phone
        %td= company.name
        %td= company.address + ", " + company.city + " - " + company.zipcode

/= link_to 'Ajouter un membre', new_workspace_member_path(@workspace), :class => 'yellow_button'

:coffeescript
  $('#companies_table').tablesorter()

app/views/credit/_credits_list.html.haml
-# encoding: utf-8 
.search_filter
  %p
    %label{:for => "credits_search_filter"} Recherche
    %input#credits_search_filter{:type => "text"}

%table.grey#credits_table
  %thead
    %tr
      %th Date
      %th Echéance
      %th Type
      %th Solde de jetons
      %th Jetons utilisés
  %tbody
    - credits_list.each do |credit|
      %tr   
        %td= credit.created_at.to_date
        %td= credit.end_date
        %td= credit.forfait.name
        %td= credit.solde_token
        %td= credit.used_token

:coffeescript
  $( ->
    $('#credits_table').tablesorter()
    searchFilter("credits_table", "credits_search_filter")
  )

app/views/credit/new.html.haml
-# encoding: utf-8 
-content_for :left_top do
  .left_submenu
    %h2.grey
    %ul
      %li.manage_pic_edit
        = link_to "Back to workspace", workspace_path(@workspace) 
      %li.manage_pic_compte_abonnement
        = link_to "Back to forfaits", workspace_forfaits_path(current_workspace_member.workspace)

-content_for :right_top do
  %h2.grey
  .grey
    %p
    %table.grey#forfaits_table
      %thead
        %tr.no_sorter
          %th ID        
          %th nb de jetons
          %th prix par jeton (HT)
          %th prix du forfait (HT)
          %th TVA
          %th prix du forfait (TTC)
          %th validité (mois)
      %tbody
        %tr
          %td=           @forfait.id
          %td=           @forfait.nb_token
          %td=           @forfait.token_price
          %td=           @forfait.global_price
          %td=           @forfait.global_price * 0.196
          %td=           @forfait.global_price * 1.196
          %td=           @forfait.validity

    %p
      %br
-content_for :workspace_content do
  %h2.grey
    Informations de facturation
  
  .grey
    %p Sélectionnez des informations de facturation déjà saisies
    = render :partial => 'credit/companies_list', :object => @workspace.companies
    %p Ou remplissez de nouvelles informations de facturation
    = semantic_form_for @new_company, :url => {:controller => "credit", :action => "create"}  do |form|
      = form.hidden_field :forfait_id, :id => "forfait_id", :name => "forfait_id", :value => @forfait.id
      = form.hidden_field :informations, :id => "informations", :name => "informations", :value => "new"
      %table.grey
        %tr
          %th Responsable :
          %td
        %tr
          %th Nom
          %td= form.text_field :lastname
        %tr
          %th Prénom
          %td= form.text_field :firstname
        %tr
          %th Téléphone
          %td= form.text_field :phone

      %table.grey
        %tr
          %th Société :
          %td
        %tr
          %th Nom
          %td= form.text_field :name
        %tr
          %th= form.label :division
          %td= form.text_field :division
        %tr
          %th= form.label :address
          %td= form.text_area :address
        %tr
          %th= form.label :city
          %td= form.text_field :city
        %tr
          %th= form.label :zipcode
          %td= form.text_field :zipcode
        %tr
          %th= form.label :country
          %td= form.text_field :country
        %tr
          %th= form.label :TVA
          %td= form.text_field :TVA
        %tr
          %th= form.label :siren
          %td= form.text_field :siren

      = submit_tag "valider", :class => 'yellow_button'
      %p
   